
version: 2

models:
  - name: stg_magasin
    description: "A starter dbt model"
    columns:
      - name: id
        description: "The unique key for this table"
        data_tests:
          - unique
          - not_null

      - name: name
        description: "name of the poi"
        data_tests:
          - not_null

      - name: latitude
        description: "latitude of the POI"
        data_tests:
          - not_null

      - name: longitude
        description: "longitude of the POI"
        data_tests:
          - not_null
