globe_itw:
  target: dev
  outputs:
    dev:
      type: snowflake
      account:  "{{ env_var('DBT_ACCOUNT_GLOBE') }}"
      user: "{{ env_var('DBT_USER_GLOBE') }}"
      password: "{{ env_var('DBT_PASSWORD_GLOBE') }}"

      role: ROLE_TYRON_FERREIRAPRO
      database: DWH_DEV_TYRON
      warehouse: COMPUTE_WH
      schema: "{{ env_var('DBT_SCHEMA') }}"
      threads: 4
      client_session_keep_alive: False
      query_tag: dbt_tyron_dev

      connect_retries: 0 # default 0
      connect_timeout: 10 # default: 10
      retry_on_database_errors: True # default: true
      retry_all: False  # default: false
      reuse_connections: True # default: True if client_session_keep_alive is False, otherwise None

    staging:
      type: snowflake
      account: "{{ env_var('DBT_ACCOUNT_GLOBE') }}"
      user: "{{ env_var('DBT_USER_GLOBE') }}"
      password: "{{ env_var('DBT_PASSWORD_GLOBE') }}"

      role: ROLE_TYRON_FERREIRAPRO
      database: DWH_DEV_TYRON
      warehouse: COMPUTE_WH
      schema: ETL
      threads: 4
      client_session_keep_alive: False
      query_tag: dbt_tyron_staging

      connect_retries: 0 # default 0
      connect_timeout: 10 # default: 10
      retry_on_database_errors: True # default: true
      retry_all: False  # default: false
      reuse_connections: True # de

    prod:
      type: snowflake
      account: "{{ env_var('DBT_ACCOUNT_GLOBE') }}"
      user: "{{ env_var('DBT_USER_GLOBE') }}"
      password: "{{ env_var('DBT_PASSWORD_GLOBE') }}"

      role: ROLE_TYRON_FERREIRAPRO
      database: DWH_DEV_TYRON
      warehouse: COMPUTE_WH
      schema: DWH_DEV_TYRON
      threads: 4
      client_session_keep_alive: False
      query_tag: dbt_tyron_prod

      connect_retries: 0 # default 0
      connect_timeout: 10 # default: 10
      retry_on_database_errors: True # default: true
      retry_all: False  # default: false
      reuse_connections: True # de

elementary:
  target: default
  outputs:
    default:
      type: snowflake
      account: "{{ env_var('DBT_ACCOUNT_GLOBE') }}"
      user: "{{ env_var('DBT_USER_GLOBE') }}"
      password: "{{ env_var('DBT_PASSWORD_GLOBE') }}"
      role: ROLE_TYRON_FERREIRAPRO
      database: DWH_DEV_TYRON
      warehouse: COMPUTE_WH
      schema: ETL
      threads: 4
      client_session_keep_alive: False
      query_tag: dbt_elementary