
version: 2

models:
  - name: stg__matchings_stores
    description: "A starter dbt model"
    data_tests:
      - elementary.volume_anomalies: &volume_config
            timestamp_column: "dbt_updated_at"
            time_bucket:
              period: day
              count: 14
      - elementary.freshness_anomalies:
          timestamp_column: "dbt_updated_at"
          config:
            severity: warn

      - elementary.schema_changes_from_baseline:
          tags: ["elementary"]

      - elementary.schema_changes:
          tags: [ "elementary" ]
          config:
            severity: warn


    columns:
      - name: id
        description: "The unique key for this table"
        data_tests:
          - not_null

      - name: name
        description: "name of the poi"
        data_tests:
          - not_null

      - name: latitude
        description: "latitude of the POI"

      - name: longitude
        description: "longitude of the POI"
